info:
  version: @project.version@
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
activemq:
  config: classpath:activemq.xml
  data: ./target/
logging:
  level:
    root: error
    com.github.macgregor.activemq: info
    org.apache.activemq.broker.BrokerService: debug
    org.apache.activemq.broker.TransportConnector: info
    org.springframework: info